# spring.datasource.url=jdbc:postgresql://localhost:1234/daily_planner
# spring.datasource.username=postgres
# spring.datasource.password=root

# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1